### ISSUE TITLE
Scaling issue-range overflow

### ISSUE THREAD

**Issue by timCF** [jj1bdx/sfmt-erlang#21]
There seems to be a bug in the scaling because the conversion to float is done by multiplying the 32 bit random output by FLOAT_CONST which is defined as (1.0/4294967295.0). Therefore the range of float values is 0.0 to 1.0 (inclusive).  The scaled number (uniform function called with an integer parameter) function is computed as “trunc(uniform() * N) +1”. So when “uniform()” produces a value of 1.0 exactly, this will result in an output of N+1 whereas the spec of the function indicates that the output will be between 1 and N, so the output will be out of range for one specific value of the RNG output (0xFFFFFFFF).

**Comment by jj1bdx** [comment]
@timCF Thanks for pointing this out. The issue has been found in #17, but it wasn't promptly fixed.

**Comment by jj1bdx** [comment]
I am thinking about making sfmt:uniform/1 output value X range to 0.0 < X < 1.0. This is consistent with rand:uniform/1, and will surely be consistent with random:uniform/1. Changing the output range consistent with the rand and random modules will solve the issue in an efficient way.

I am testing the random:uniform/1 function by running a simulation so that the output Y range is 0.0 < Y < 1.0; the simulation will be finished within a day or a couple of days. After verifying the simulation output, I will update and test the sfmt-erlang code.

**Comment by jj1bdx** [comment]
This issue has been fixed in https://github.com/jj1bdx/sfmt-erlang/commit/bbfa9e06da890f6a41527557ea2934c0a265c7eb and https://github.com/jj1bdx/sfmt-erlang/commit/64a5aa2c80739d2eedd4ed0990b6decdcdb20f3a.
Issue closed.

**Comment by timCF** [comment]
thx!

**Comment by jj1bdx** [comment]
Note for myself: AS183 aka `random:uniform/0` output R range is 0.0 < R < 1.0, by a brute-force calculation of all AS183 possible value sets (~ 7x(10^12) cases).
